FROM golang:1.24.2-alpine3.21 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY ./server ./server
COPY ./common ./common

RUN go build -o server.bin ./server



FROM busybox:latest

WORKDIR /app

COPY --from=builder /app/server.bin ./

ENTRYPOINT [ "./server.bin" ]
