// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/stages/epsilon.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Epsilon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Epsilon_Data        `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Epsilon) Reset() {
	*x = Epsilon{}
	mi := &file_proto_stages_epsilon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Epsilon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Epsilon) ProtoMessage() {}

func (x *Epsilon) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stages_epsilon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Epsilon.ProtoReflect.Descriptor instead.
func (*Epsilon) Descriptor() ([]byte, []int) {
	return file_proto_stages_epsilon_proto_rawDescGZIP(), []int{0}
}

func (x *Epsilon) GetData() []*Epsilon_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type Epsilon_Data struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProdCountry     string                 `protobuf:"bytes,1,opt,name=prod_country,json=prodCountry,proto3" json:"prod_country,omitempty"`
	TotalInvestment uint64                 `protobuf:"varint,2,opt,name=total_investment,json=totalInvestment,proto3" json:"total_investment,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Epsilon_Data) Reset() {
	*x = Epsilon_Data{}
	mi := &file_proto_stages_epsilon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Epsilon_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Epsilon_Data) ProtoMessage() {}

func (x *Epsilon_Data) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stages_epsilon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Epsilon_Data.ProtoReflect.Descriptor instead.
func (*Epsilon_Data) Descriptor() ([]byte, []int) {
	return file_proto_stages_epsilon_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Epsilon_Data) GetProdCountry() string {
	if x != nil {
		return x.ProdCountry
	}
	return ""
}

func (x *Epsilon_Data) GetTotalInvestment() uint64 {
	if x != nil {
		return x.TotalInvestment
	}
	return 0
}

var File_proto_stages_epsilon_proto protoreflect.FileDescriptor

const file_proto_stages_epsilon_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/stages/epsilon.proto\"\x82\x01\n" +
	"\aEpsilon\x12!\n" +
	"\x04data\x18\x01 \x03(\v2\r.Epsilon.DataR\x04data\x1aT\n" +
	"\x04Data\x12!\n" +
	"\fprod_country\x18\x01 \x01(\tR\vprodCountry\x12)\n" +
	"\x10total_investment\x18\x02 \x01(\x04R\x0ftotalInvestmentB\x1fZ\x1dcommon/communication/protocolb\x06proto3"

var (
	file_proto_stages_epsilon_proto_rawDescOnce sync.Once
	file_proto_stages_epsilon_proto_rawDescData []byte
)

func file_proto_stages_epsilon_proto_rawDescGZIP() []byte {
	file_proto_stages_epsilon_proto_rawDescOnce.Do(func() {
		file_proto_stages_epsilon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_stages_epsilon_proto_rawDesc), len(file_proto_stages_epsilon_proto_rawDesc)))
	})
	return file_proto_stages_epsilon_proto_rawDescData
}

var file_proto_stages_epsilon_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_stages_epsilon_proto_goTypes = []any{
	(*Epsilon)(nil),      // 0: Epsilon
	(*Epsilon_Data)(nil), // 1: Epsilon.Data
}
var file_proto_stages_epsilon_proto_depIdxs = []int32{
	1, // 0: Epsilon.data:type_name -> Epsilon.Data
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_stages_epsilon_proto_init() }
func file_proto_stages_epsilon_proto_init() {
	if File_proto_stages_epsilon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_stages_epsilon_proto_rawDesc), len(file_proto_stages_epsilon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_stages_epsilon_proto_goTypes,
		DependencyIndexes: file_proto_stages_epsilon_proto_depIdxs,
		MessageInfos:      file_proto_stages_epsilon_proto_msgTypes,
	}.Build()
	File_proto_stages_epsilon_proto = out.File
	file_proto_stages_epsilon_proto_goTypes = nil
	file_proto_stages_epsilon_proto_depIdxs = nil
}
