// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/stages/eta.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Eta_1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Eta_1_Data          `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Eta_1) Reset() {
	*x = Eta_1{}
	mi := &file_proto_stages_eta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Eta_1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Eta_1) ProtoMessage() {}

func (x *Eta_1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stages_eta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Eta_1.ProtoReflect.Descriptor instead.
func (*Eta_1) Descriptor() ([]byte, []int) {
	return file_proto_stages_eta_proto_rawDescGZIP(), []int{0}
}

func (x *Eta_1) GetData() []*Eta_1_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type Eta_2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Eta_2_Data          `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Eta_2) Reset() {
	*x = Eta_2{}
	mi := &file_proto_stages_eta_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Eta_2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Eta_2) ProtoMessage() {}

func (x *Eta_2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stages_eta_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Eta_2.ProtoReflect.Descriptor instead.
func (*Eta_2) Descriptor() ([]byte, []int) {
	return file_proto_stages_eta_proto_rawDescGZIP(), []int{1}
}

func (x *Eta_2) GetData() []*Eta_2_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type Eta_3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Eta_3_Data          `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Eta_3) Reset() {
	*x = Eta_3{}
	mi := &file_proto_stages_eta_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Eta_3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Eta_3) ProtoMessage() {}

func (x *Eta_3) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stages_eta_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Eta_3.ProtoReflect.Descriptor instead.
func (*Eta_3) Descriptor() ([]byte, []int) {
	return file_proto_stages_eta_proto_rawDescGZIP(), []int{2}
}

func (x *Eta_3) GetData() []*Eta_3_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type Eta_1_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       string                 `protobuf:"bytes,1,opt,name=movieId,proto3" json:"movieId,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Rating        float32                `protobuf:"fixed32,3,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Eta_1_Data) Reset() {
	*x = Eta_1_Data{}
	mi := &file_proto_stages_eta_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Eta_1_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Eta_1_Data) ProtoMessage() {}

func (x *Eta_1_Data) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stages_eta_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Eta_1_Data.ProtoReflect.Descriptor instead.
func (*Eta_1_Data) Descriptor() ([]byte, []int) {
	return file_proto_stages_eta_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Eta_1_Data) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *Eta_1_Data) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Eta_1_Data) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type Eta_2_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       string                 `protobuf:"bytes,1,opt,name=movieId,proto3" json:"movieId,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Rating        float64                `protobuf:"fixed64,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Count         uint32                 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Eta_2_Data) Reset() {
	*x = Eta_2_Data{}
	mi := &file_proto_stages_eta_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Eta_2_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Eta_2_Data) ProtoMessage() {}

func (x *Eta_2_Data) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stages_eta_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Eta_2_Data.ProtoReflect.Descriptor instead.
func (*Eta_2_Data) Descriptor() ([]byte, []int) {
	return file_proto_stages_eta_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Eta_2_Data) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *Eta_2_Data) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Eta_2_Data) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Eta_2_Data) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type Eta_3_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       string                 `protobuf:"bytes,1,opt,name=movieId,proto3" json:"movieId,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Rating        float64                `protobuf:"fixed64,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Count         uint32                 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Eta_3_Data) Reset() {
	*x = Eta_3_Data{}
	mi := &file_proto_stages_eta_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Eta_3_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Eta_3_Data) ProtoMessage() {}

func (x *Eta_3_Data) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stages_eta_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Eta_3_Data.ProtoReflect.Descriptor instead.
func (*Eta_3_Data) Descriptor() ([]byte, []int) {
	return file_proto_stages_eta_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Eta_3_Data) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *Eta_3_Data) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Eta_3_Data) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Eta_3_Data) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_proto_stages_eta_proto protoreflect.FileDescriptor

const file_proto_stages_eta_proto_rawDesc = "" +
	"\n" +
	"\x16proto/stages/eta.proto\"x\n" +
	"\x05Eta_1\x12\x1f\n" +
	"\x04data\x18\x01 \x03(\v2\v.Eta_1.DataR\x04data\x1aN\n" +
	"\x04Data\x12\x18\n" +
	"\amovieId\x18\x01 \x01(\tR\amovieId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\x02R\x06rating\"\x8e\x01\n" +
	"\x05Eta_2\x12\x1f\n" +
	"\x04data\x18\x01 \x03(\v2\v.Eta_2.DataR\x04data\x1ad\n" +
	"\x04Data\x12\x18\n" +
	"\amovieId\x18\x01 \x01(\tR\amovieId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\x01R\x06rating\x12\x14\n" +
	"\x05count\x18\x04 \x01(\rR\x05count\"\x8e\x01\n" +
	"\x05Eta_3\x12\x1f\n" +
	"\x04data\x18\x01 \x03(\v2\v.Eta_3.DataR\x04data\x1ad\n" +
	"\x04Data\x12\x18\n" +
	"\amovieId\x18\x01 \x01(\tR\amovieId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\x01R\x06rating\x12\x14\n" +
	"\x05count\x18\x04 \x01(\rR\x05countB\x1fZ\x1dcommon/communication/protocolb\x06proto3"

var (
	file_proto_stages_eta_proto_rawDescOnce sync.Once
	file_proto_stages_eta_proto_rawDescData []byte
)

func file_proto_stages_eta_proto_rawDescGZIP() []byte {
	file_proto_stages_eta_proto_rawDescOnce.Do(func() {
		file_proto_stages_eta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_stages_eta_proto_rawDesc), len(file_proto_stages_eta_proto_rawDesc)))
	})
	return file_proto_stages_eta_proto_rawDescData
}

var file_proto_stages_eta_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_stages_eta_proto_goTypes = []any{
	(*Eta_1)(nil),      // 0: Eta_1
	(*Eta_2)(nil),      // 1: Eta_2
	(*Eta_3)(nil),      // 2: Eta_3
	(*Eta_1_Data)(nil), // 3: Eta_1.Data
	(*Eta_2_Data)(nil), // 4: Eta_2.Data
	(*Eta_3_Data)(nil), // 5: Eta_3.Data
}
var file_proto_stages_eta_proto_depIdxs = []int32{
	3, // 0: Eta_1.data:type_name -> Eta_1.Data
	4, // 1: Eta_2.data:type_name -> Eta_2.Data
	5, // 2: Eta_3.data:type_name -> Eta_3.Data
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_stages_eta_proto_init() }
func file_proto_stages_eta_proto_init() {
	if File_proto_stages_eta_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_stages_eta_proto_rawDesc), len(file_proto_stages_eta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_stages_eta_proto_goTypes,
		DependencyIndexes: file_proto_stages_eta_proto_depIdxs,
		MessageInfos:      file_proto_stages_eta_proto_msgTypes,
	}.Build()
	File_proto_stages_eta_proto = out.File
	file_proto_stages_eta_proto_goTypes = nil
	file_proto_stages_eta_proto_depIdxs = nil
}
