// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/stages/gamma.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Gamma struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Gamma_Data          `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gamma) Reset() {
	*x = Gamma{}
	mi := &file_proto_stages_gamma_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gamma) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gamma) ProtoMessage() {}

func (x *Gamma) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stages_gamma_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gamma.ProtoReflect.Descriptor instead.
func (*Gamma) Descriptor() ([]byte, []int) {
	return file_proto_stages_gamma_proto_rawDescGZIP(), []int{0}
}

func (x *Gamma) GetData() []*Gamma_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type Gamma_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProdCountries []string               `protobuf:"bytes,2,rep,name=prod_countries,json=prodCountries,proto3" json:"prod_countries,omitempty"`
	Budget        uint64                 `protobuf:"varint,3,opt,name=budget,proto3" json:"budget,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gamma_Data) Reset() {
	*x = Gamma_Data{}
	mi := &file_proto_stages_gamma_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gamma_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gamma_Data) ProtoMessage() {}

func (x *Gamma_Data) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stages_gamma_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gamma_Data.ProtoReflect.Descriptor instead.
func (*Gamma_Data) Descriptor() ([]byte, []int) {
	return file_proto_stages_gamma_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Gamma_Data) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Gamma_Data) GetProdCountries() []string {
	if x != nil {
		return x.ProdCountries
	}
	return nil
}

func (x *Gamma_Data) GetBudget() uint64 {
	if x != nil {
		return x.Budget
	}
	return 0
}

var File_proto_stages_gamma_proto protoreflect.FileDescriptor

const file_proto_stages_gamma_proto_rawDesc = "" +
	"\n" +
	"\x18proto/stages/gamma.proto\"\x7f\n" +
	"\x05Gamma\x12\x1f\n" +
	"\x04data\x18\x01 \x03(\v2\v.Gamma.DataR\x04data\x1aU\n" +
	"\x04Data\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eprod_countries\x18\x02 \x03(\tR\rprodCountries\x12\x16\n" +
	"\x06budget\x18\x03 \x01(\x04R\x06budgetB\x1fZ\x1dcommon/communication/protocolb\x06proto3"

var (
	file_proto_stages_gamma_proto_rawDescOnce sync.Once
	file_proto_stages_gamma_proto_rawDescData []byte
)

func file_proto_stages_gamma_proto_rawDescGZIP() []byte {
	file_proto_stages_gamma_proto_rawDescOnce.Do(func() {
		file_proto_stages_gamma_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_stages_gamma_proto_rawDesc), len(file_proto_stages_gamma_proto_rawDesc)))
	})
	return file_proto_stages_gamma_proto_rawDescData
}

var file_proto_stages_gamma_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_stages_gamma_proto_goTypes = []any{
	(*Gamma)(nil),      // 0: Gamma
	(*Gamma_Data)(nil), // 1: Gamma.Data
}
var file_proto_stages_gamma_proto_depIdxs = []int32{
	1, // 0: Gamma.data:type_name -> Gamma.Data
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_stages_gamma_proto_init() }
func file_proto_stages_gamma_proto_init() {
	if File_proto_stages_gamma_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_stages_gamma_proto_rawDesc), len(file_proto_stages_gamma_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_stages_gamma_proto_goTypes,
		DependencyIndexes: file_proto_stages_gamma_proto_depIdxs,
		MessageInfos:      file_proto_stages_gamma_proto_msgTypes,
	}.Build()
	File_proto_stages_gamma_proto = out.File
	file_proto_stages_gamma_proto_goTypes = nil
	file_proto_stages_gamma_proto_depIdxs = nil
}
