// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/health.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_health_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerName string                 `protobuf:"bytes,1,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_health_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

type HealthMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*HealthMessage_PingRequest
	//	*HealthMessage_PingResponse
	Message       isHealthMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthMessage) Reset() {
	*x = HealthMessage{}
	mi := &file_proto_health_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthMessage) ProtoMessage() {}

func (x *HealthMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_health_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthMessage.ProtoReflect.Descriptor instead.
func (*HealthMessage) Descriptor() ([]byte, []int) {
	return file_proto_health_proto_rawDescGZIP(), []int{2}
}

func (x *HealthMessage) GetMessage() isHealthMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *HealthMessage) GetPingRequest() *PingRequest {
	if x != nil {
		if x, ok := x.Message.(*HealthMessage_PingRequest); ok {
			return x.PingRequest
		}
	}
	return nil
}

func (x *HealthMessage) GetPingResponse() *PingResponse {
	if x != nil {
		if x, ok := x.Message.(*HealthMessage_PingResponse); ok {
			return x.PingResponse
		}
	}
	return nil
}

type isHealthMessage_Message interface {
	isHealthMessage_Message()
}

type HealthMessage_PingRequest struct {
	PingRequest *PingRequest `protobuf:"bytes,2,opt,name=ping_request,json=pingRequest,proto3,oneof"`
}

type HealthMessage_PingResponse struct {
	PingResponse *PingResponse `protobuf:"bytes,3,opt,name=ping_response,json=pingResponse,proto3,oneof"`
}

func (*HealthMessage_PingRequest) isHealthMessage_Message() {}

func (*HealthMessage_PingResponse) isHealthMessage_Message() {}

var File_proto_health_proto protoreflect.FileDescriptor

const file_proto_health_proto_rawDesc = "" +
	"\n" +
	"\x12proto/health.proto\"\r\n" +
	"\vPingRequest\"5\n" +
	"\fPingResponse\x12%\n" +
	"\x0econtainer_name\x18\x01 \x01(\tR\rcontainerName\"\x83\x01\n" +
	"\rHealthMessage\x121\n" +
	"\fping_request\x18\x02 \x01(\v2\f.PingRequestH\x00R\vpingRequest\x124\n" +
	"\rping_response\x18\x03 \x01(\v2\r.PingResponseH\x00R\fpingResponseB\t\n" +
	"\amessageB\x1fZ\x1dcommon/communication/protocolb\x06proto3"

var (
	file_proto_health_proto_rawDescOnce sync.Once
	file_proto_health_proto_rawDescData []byte
)

func file_proto_health_proto_rawDescGZIP() []byte {
	file_proto_health_proto_rawDescOnce.Do(func() {
		file_proto_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_health_proto_rawDesc), len(file_proto_health_proto_rawDesc)))
	})
	return file_proto_health_proto_rawDescData
}

var file_proto_health_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_health_proto_goTypes = []any{
	(*PingRequest)(nil),   // 0: PingRequest
	(*PingResponse)(nil),  // 1: PingResponse
	(*HealthMessage)(nil), // 2: HealthMessage
}
var file_proto_health_proto_depIdxs = []int32{
	0, // 0: HealthMessage.ping_request:type_name -> PingRequest
	1, // 1: HealthMessage.ping_response:type_name -> PingResponse
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_health_proto_init() }
func file_proto_health_proto_init() {
	if File_proto_health_proto != nil {
		return
	}
	file_proto_health_proto_msgTypes[2].OneofWrappers = []any{
		(*HealthMessage_PingRequest)(nil),
		(*HealthMessage_PingResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_health_proto_rawDesc), len(file_proto_health_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_health_proto_goTypes,
		DependencyIndexes: file_proto_health_proto_depIdxs,
		MessageInfos:      file_proto_health_proto_msgTypes,
	}.Build()
	File_proto_health_proto = out.File
	file_proto_health_proto_goTypes = nil
	file_proto_health_proto_depIdxs = nil
}
