// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/health_internal.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        map[string]uint32      `protobuf:"bytes,1,rep,name=status,proto3" json:"status,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // key: container_name, value: missed pings count
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_proto_health_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_proto_health_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_proto_health_internal_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetStatus() map[string]uint32 {
	if x != nil {
		return x.Status
	}
	return nil
}

type Election struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HealtcheckerId string                 `protobuf:"bytes,1,opt,name=healtchecker_id,json=healtcheckerId,proto3" json:"healtchecker_id,omitempty"` // ID of the healthchecker that initiated the election
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Election) Reset() {
	*x = Election{}
	mi := &file_proto_health_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Election) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Election) ProtoMessage() {}

func (x *Election) ProtoReflect() protoreflect.Message {
	mi := &file_proto_health_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Election.ProtoReflect.Descriptor instead.
func (*Election) Descriptor() ([]byte, []int) {
	return file_proto_health_internal_proto_rawDescGZIP(), []int{1}
}

func (x *Election) GetHealtcheckerId() string {
	if x != nil {
		return x.HealtcheckerId
	}
	return ""
}

type Leader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaderId      string                 `protobuf:"bytes,1,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"` // ID of the new leader
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Leader) Reset() {
	*x = Leader{}
	mi := &file_proto_health_internal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Leader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Leader) ProtoMessage() {}

func (x *Leader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_health_internal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Leader.ProtoReflect.Descriptor instead.
func (*Leader) Descriptor() ([]byte, []int) {
	return file_proto_health_internal_proto_rawDescGZIP(), []int{2}
}

func (x *Leader) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

type HealthInternalMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*HealthInternalMessage_Status
	//	*HealthInternalMessage_Election
	//	*HealthInternalMessage_Leader
	Message       isHealthInternalMessage_Message `protobuf_oneof:"message"`
	SenderId      string                          `protobuf:"bytes,4,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"` // ID of the sender of this message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthInternalMessage) Reset() {
	*x = HealthInternalMessage{}
	mi := &file_proto_health_internal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthInternalMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthInternalMessage) ProtoMessage() {}

func (x *HealthInternalMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_health_internal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthInternalMessage.ProtoReflect.Descriptor instead.
func (*HealthInternalMessage) Descriptor() ([]byte, []int) {
	return file_proto_health_internal_proto_rawDescGZIP(), []int{3}
}

func (x *HealthInternalMessage) GetMessage() isHealthInternalMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *HealthInternalMessage) GetStatus() *Status {
	if x != nil {
		if x, ok := x.Message.(*HealthInternalMessage_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *HealthInternalMessage) GetElection() *Election {
	if x != nil {
		if x, ok := x.Message.(*HealthInternalMessage_Election); ok {
			return x.Election
		}
	}
	return nil
}

func (x *HealthInternalMessage) GetLeader() *Leader {
	if x != nil {
		if x, ok := x.Message.(*HealthInternalMessage_Leader); ok {
			return x.Leader
		}
	}
	return nil
}

func (x *HealthInternalMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

type isHealthInternalMessage_Message interface {
	isHealthInternalMessage_Message()
}

type HealthInternalMessage_Status struct {
	Status *Status `protobuf:"bytes,1,opt,name=status,proto3,oneof"` // Contains the status of healthcheckers
}

type HealthInternalMessage_Election struct {
	Election *Election `protobuf:"bytes,2,opt,name=election,proto3,oneof"` // Contains information about an election
}

type HealthInternalMessage_Leader struct {
	Leader *Leader `protobuf:"bytes,3,opt,name=leader,proto3,oneof"` // Contains information about the new leader
}

func (*HealthInternalMessage_Status) isHealthInternalMessage_Message() {}

func (*HealthInternalMessage_Election) isHealthInternalMessage_Message() {}

func (*HealthInternalMessage_Leader) isHealthInternalMessage_Message() {}

var File_proto_health_internal_proto protoreflect.FileDescriptor

const file_proto_health_internal_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/health_internal.proto\"p\n" +
	"\x06Status\x12+\n" +
	"\x06status\x18\x01 \x03(\v2\x13.Status.StatusEntryR\x06status\x1a9\n" +
	"\vStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"3\n" +
	"\bElection\x12'\n" +
	"\x0fhealtchecker_id\x18\x01 \x01(\tR\x0ehealtcheckerId\"%\n" +
	"\x06Leader\x12\x1b\n" +
	"\tleader_id\x18\x01 \x01(\tR\bleaderId\"\xae\x01\n" +
	"\x15HealthInternalMessage\x12!\n" +
	"\x06status\x18\x01 \x01(\v2\a.StatusH\x00R\x06status\x12'\n" +
	"\belection\x18\x02 \x01(\v2\t.ElectionH\x00R\belection\x12!\n" +
	"\x06leader\x18\x03 \x01(\v2\a.LeaderH\x00R\x06leader\x12\x1b\n" +
	"\tsender_id\x18\x04 \x01(\tR\bsenderIdB\t\n" +
	"\amessageB\x1fZ\x1dcommon/communication/protocolb\x06proto3"

var (
	file_proto_health_internal_proto_rawDescOnce sync.Once
	file_proto_health_internal_proto_rawDescData []byte
)

func file_proto_health_internal_proto_rawDescGZIP() []byte {
	file_proto_health_internal_proto_rawDescOnce.Do(func() {
		file_proto_health_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_health_internal_proto_rawDesc), len(file_proto_health_internal_proto_rawDesc)))
	})
	return file_proto_health_internal_proto_rawDescData
}

var file_proto_health_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_health_internal_proto_goTypes = []any{
	(*Status)(nil),                // 0: Status
	(*Election)(nil),              // 1: Election
	(*Leader)(nil),                // 2: Leader
	(*HealthInternalMessage)(nil), // 3: HealthInternalMessage
	nil,                           // 4: Status.StatusEntry
}
var file_proto_health_internal_proto_depIdxs = []int32{
	4, // 0: Status.status:type_name -> Status.StatusEntry
	0, // 1: HealthInternalMessage.status:type_name -> Status
	1, // 2: HealthInternalMessage.election:type_name -> Election
	2, // 3: HealthInternalMessage.leader:type_name -> Leader
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_health_internal_proto_init() }
func file_proto_health_internal_proto_init() {
	if File_proto_health_internal_proto != nil {
		return
	}
	file_proto_health_internal_proto_msgTypes[3].OneofWrappers = []any{
		(*HealthInternalMessage_Status)(nil),
		(*HealthInternalMessage_Election)(nil),
		(*HealthInternalMessage_Leader)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_health_internal_proto_rawDesc), len(file_proto_health_internal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_health_internal_proto_goTypes,
		DependencyIndexes: file_proto_health_internal_proto_depIdxs,
		MessageInfos:      file_proto_health_internal_proto_msgTypes,
	}.Build()
	File_proto_health_internal_proto = out.File
	file_proto_health_internal_proto_goTypes = nil
	file_proto_health_internal_proto_depIdxs = nil
}
