// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/stages/iota.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Iota struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Iota_Data           `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Iota) Reset() {
	*x = Iota{}
	mi := &file_proto_stages_iota_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Iota) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Iota) ProtoMessage() {}

func (x *Iota) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stages_iota_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Iota.ProtoReflect.Descriptor instead.
func (*Iota) Descriptor() ([]byte, []int) {
	return file_proto_stages_iota_proto_rawDescGZIP(), []int{0}
}

func (x *Iota) GetData() []*Iota_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type Iota_Data struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*Iota_Data_Movie_
	//	*Iota_Data_Actor_
	Data          isIota_Data_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Iota_Data) Reset() {
	*x = Iota_Data{}
	mi := &file_proto_stages_iota_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Iota_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Iota_Data) ProtoMessage() {}

func (x *Iota_Data) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stages_iota_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Iota_Data.ProtoReflect.Descriptor instead.
func (*Iota_Data) Descriptor() ([]byte, []int) {
	return file_proto_stages_iota_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Iota_Data) GetData() isIota_Data_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Iota_Data) GetMovie() *Iota_Data_Movie {
	if x != nil {
		if x, ok := x.Data.(*Iota_Data_Movie_); ok {
			return x.Movie
		}
	}
	return nil
}

func (x *Iota_Data) GetActor() *Iota_Data_Actor {
	if x != nil {
		if x, ok := x.Data.(*Iota_Data_Actor_); ok {
			return x.Actor
		}
	}
	return nil
}

type isIota_Data_Data interface {
	isIota_Data_Data()
}

type Iota_Data_Movie_ struct {
	Movie *Iota_Data_Movie `protobuf:"bytes,1,opt,name=movie,proto3,oneof"`
}

type Iota_Data_Actor_ struct {
	Actor *Iota_Data_Actor `protobuf:"bytes,2,opt,name=actor,proto3,oneof"`
}

func (*Iota_Data_Movie_) isIota_Data_Data() {}

func (*Iota_Data_Actor_) isIota_Data_Data() {}

type Iota_Data_Movie struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       string                 `protobuf:"bytes,1,opt,name=movieId,proto3" json:"movieId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Iota_Data_Movie) Reset() {
	*x = Iota_Data_Movie{}
	mi := &file_proto_stages_iota_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Iota_Data_Movie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Iota_Data_Movie) ProtoMessage() {}

func (x *Iota_Data_Movie) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stages_iota_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Iota_Data_Movie.ProtoReflect.Descriptor instead.
func (*Iota_Data_Movie) Descriptor() ([]byte, []int) {
	return file_proto_stages_iota_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Iota_Data_Movie) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

type Iota_Data_Actor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       string                 `protobuf:"bytes,1,opt,name=movieId,proto3" json:"movieId,omitempty"`
	ActorId       string                 `protobuf:"bytes,2,opt,name=actorId,proto3" json:"actorId,omitempty"`
	ActorName     string                 `protobuf:"bytes,3,opt,name=actorName,proto3" json:"actorName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Iota_Data_Actor) Reset() {
	*x = Iota_Data_Actor{}
	mi := &file_proto_stages_iota_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Iota_Data_Actor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Iota_Data_Actor) ProtoMessage() {}

func (x *Iota_Data_Actor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stages_iota_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Iota_Data_Actor.ProtoReflect.Descriptor instead.
func (*Iota_Data_Actor) Descriptor() ([]byte, []int) {
	return file_proto_stages_iota_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *Iota_Data_Actor) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *Iota_Data_Actor) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *Iota_Data_Actor) GetActorName() string {
	if x != nil {
		return x.ActorName
	}
	return ""
}

var File_proto_stages_iota_proto protoreflect.FileDescriptor

const file_proto_stages_iota_proto_rawDesc = "" +
	"\n" +
	"\x17proto/stages/iota.proto\"\x89\x02\n" +
	"\x04Iota\x12\x1e\n" +
	"\x04data\x18\x01 \x03(\v2\n" +
	".Iota.DataR\x04data\x1a\xe0\x01\n" +
	"\x04Data\x12(\n" +
	"\x05movie\x18\x01 \x01(\v2\x10.Iota.Data.MovieH\x00R\x05movie\x12(\n" +
	"\x05actor\x18\x02 \x01(\v2\x10.Iota.Data.ActorH\x00R\x05actor\x1a!\n" +
	"\x05Movie\x12\x18\n" +
	"\amovieId\x18\x01 \x01(\tR\amovieId\x1aY\n" +
	"\x05Actor\x12\x18\n" +
	"\amovieId\x18\x01 \x01(\tR\amovieId\x12\x18\n" +
	"\aactorId\x18\x02 \x01(\tR\aactorId\x12\x1c\n" +
	"\tactorName\x18\x03 \x01(\tR\tactorNameB\x06\n" +
	"\x04dataB\x1fZ\x1dcommon/communication/protocolb\x06proto3"

var (
	file_proto_stages_iota_proto_rawDescOnce sync.Once
	file_proto_stages_iota_proto_rawDescData []byte
)

func file_proto_stages_iota_proto_rawDescGZIP() []byte {
	file_proto_stages_iota_proto_rawDescOnce.Do(func() {
		file_proto_stages_iota_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_stages_iota_proto_rawDesc), len(file_proto_stages_iota_proto_rawDesc)))
	})
	return file_proto_stages_iota_proto_rawDescData
}

var file_proto_stages_iota_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_stages_iota_proto_goTypes = []any{
	(*Iota)(nil),            // 0: Iota
	(*Iota_Data)(nil),       // 1: Iota.Data
	(*Iota_Data_Movie)(nil), // 2: Iota.Data.Movie
	(*Iota_Data_Actor)(nil), // 3: Iota.Data.Actor
}
var file_proto_stages_iota_proto_depIdxs = []int32{
	1, // 0: Iota.data:type_name -> Iota.Data
	2, // 1: Iota.Data.movie:type_name -> Iota.Data.Movie
	3, // 2: Iota.Data.actor:type_name -> Iota.Data.Actor
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_stages_iota_proto_init() }
func file_proto_stages_iota_proto_init() {
	if File_proto_stages_iota_proto != nil {
		return
	}
	file_proto_stages_iota_proto_msgTypes[1].OneofWrappers = []any{
		(*Iota_Data_Movie_)(nil),
		(*Iota_Data_Actor_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_stages_iota_proto_rawDesc), len(file_proto_stages_iota_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_stages_iota_proto_goTypes,
		DependencyIndexes: file_proto_stages_iota_proto_depIdxs,
		MessageInfos:      file_proto_stages_iota_proto_msgTypes,
	}.Build()
	File_proto_stages_iota_proto = out.File
	file_proto_stages_iota_proto_goTypes = nil
	file_proto_stages_iota_proto_depIdxs = nil
}
