// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/stages/kappa.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Kappa_1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Kappa_1_Data        `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kappa_1) Reset() {
	*x = Kappa_1{}
	mi := &file_proto_stages_kappa_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kappa_1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kappa_1) ProtoMessage() {}

func (x *Kappa_1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stages_kappa_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kappa_1.ProtoReflect.Descriptor instead.
func (*Kappa_1) Descriptor() ([]byte, []int) {
	return file_proto_stages_kappa_proto_rawDescGZIP(), []int{0}
}

func (x *Kappa_1) GetData() []*Kappa_1_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type Kappa_2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Kappa_2_Data        `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kappa_2) Reset() {
	*x = Kappa_2{}
	mi := &file_proto_stages_kappa_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kappa_2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kappa_2) ProtoMessage() {}

func (x *Kappa_2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stages_kappa_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kappa_2.ProtoReflect.Descriptor instead.
func (*Kappa_2) Descriptor() ([]byte, []int) {
	return file_proto_stages_kappa_proto_rawDescGZIP(), []int{1}
}

func (x *Kappa_2) GetData() []*Kappa_2_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type Kappa_3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Kappa_3_Data        `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kappa_3) Reset() {
	*x = Kappa_3{}
	mi := &file_proto_stages_kappa_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kappa_3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kappa_3) ProtoMessage() {}

func (x *Kappa_3) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stages_kappa_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kappa_3.ProtoReflect.Descriptor instead.
func (*Kappa_3) Descriptor() ([]byte, []int) {
	return file_proto_stages_kappa_proto_rawDescGZIP(), []int{2}
}

func (x *Kappa_3) GetData() []*Kappa_3_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type Kappa_1_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       string                 `protobuf:"bytes,1,opt,name=movieId,proto3" json:"movieId,omitempty"`
	ActorId       string                 `protobuf:"bytes,2,opt,name=actorId,proto3" json:"actorId,omitempty"`
	ActorName     string                 `protobuf:"bytes,3,opt,name=actorName,proto3" json:"actorName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kappa_1_Data) Reset() {
	*x = Kappa_1_Data{}
	mi := &file_proto_stages_kappa_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kappa_1_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kappa_1_Data) ProtoMessage() {}

func (x *Kappa_1_Data) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stages_kappa_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kappa_1_Data.ProtoReflect.Descriptor instead.
func (*Kappa_1_Data) Descriptor() ([]byte, []int) {
	return file_proto_stages_kappa_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Kappa_1_Data) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *Kappa_1_Data) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *Kappa_1_Data) GetActorName() string {
	if x != nil {
		return x.ActorName
	}
	return ""
}

type Kappa_2_Data struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ActorId               string                 `protobuf:"bytes,1,opt,name=actorId,proto3" json:"actorId,omitempty"`
	ActorName             string                 `protobuf:"bytes,2,opt,name=actorName,proto3" json:"actorName,omitempty"`
	PartialParticipations uint64                 `protobuf:"varint,3,opt,name=partial_participations,json=partialParticipations,proto3" json:"partial_participations,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Kappa_2_Data) Reset() {
	*x = Kappa_2_Data{}
	mi := &file_proto_stages_kappa_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kappa_2_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kappa_2_Data) ProtoMessage() {}

func (x *Kappa_2_Data) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stages_kappa_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kappa_2_Data.ProtoReflect.Descriptor instead.
func (*Kappa_2_Data) Descriptor() ([]byte, []int) {
	return file_proto_stages_kappa_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Kappa_2_Data) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *Kappa_2_Data) GetActorName() string {
	if x != nil {
		return x.ActorName
	}
	return ""
}

func (x *Kappa_2_Data) GetPartialParticipations() uint64 {
	if x != nil {
		return x.PartialParticipations
	}
	return 0
}

type Kappa_3_Data struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ActorId               string                 `protobuf:"bytes,1,opt,name=actorId,proto3" json:"actorId,omitempty"`
	ActorName             string                 `protobuf:"bytes,2,opt,name=actorName,proto3" json:"actorName,omitempty"`
	PartialParticipations uint64                 `protobuf:"varint,3,opt,name=partial_participations,json=partialParticipations,proto3" json:"partial_participations,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Kappa_3_Data) Reset() {
	*x = Kappa_3_Data{}
	mi := &file_proto_stages_kappa_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kappa_3_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kappa_3_Data) ProtoMessage() {}

func (x *Kappa_3_Data) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stages_kappa_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kappa_3_Data.ProtoReflect.Descriptor instead.
func (*Kappa_3_Data) Descriptor() ([]byte, []int) {
	return file_proto_stages_kappa_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Kappa_3_Data) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *Kappa_3_Data) GetActorName() string {
	if x != nil {
		return x.ActorName
	}
	return ""
}

func (x *Kappa_3_Data) GetPartialParticipations() uint64 {
	if x != nil {
		return x.PartialParticipations
	}
	return 0
}

var File_proto_stages_kappa_proto protoreflect.FileDescriptor

const file_proto_stages_kappa_proto_rawDesc = "" +
	"\n" +
	"\x18proto/stages/kappa.proto\"\x86\x01\n" +
	"\aKappa_1\x12!\n" +
	"\x04data\x18\x01 \x03(\v2\r.Kappa_1.DataR\x04data\x1aX\n" +
	"\x04Data\x12\x18\n" +
	"\amovieId\x18\x01 \x01(\tR\amovieId\x12\x18\n" +
	"\aactorId\x18\x02 \x01(\tR\aactorId\x12\x1c\n" +
	"\tactorName\x18\x03 \x01(\tR\tactorName\"\xa3\x01\n" +
	"\aKappa_2\x12!\n" +
	"\x04data\x18\x01 \x03(\v2\r.Kappa_2.DataR\x04data\x1au\n" +
	"\x04Data\x12\x18\n" +
	"\aactorId\x18\x01 \x01(\tR\aactorId\x12\x1c\n" +
	"\tactorName\x18\x02 \x01(\tR\tactorName\x125\n" +
	"\x16partial_participations\x18\x03 \x01(\x04R\x15partialParticipations\"\xa3\x01\n" +
	"\aKappa_3\x12!\n" +
	"\x04data\x18\x01 \x03(\v2\r.Kappa_3.DataR\x04data\x1au\n" +
	"\x04Data\x12\x18\n" +
	"\aactorId\x18\x01 \x01(\tR\aactorId\x12\x1c\n" +
	"\tactorName\x18\x02 \x01(\tR\tactorName\x125\n" +
	"\x16partial_participations\x18\x03 \x01(\x04R\x15partialParticipationsB\x1fZ\x1dcommon/communication/protocolb\x06proto3"

var (
	file_proto_stages_kappa_proto_rawDescOnce sync.Once
	file_proto_stages_kappa_proto_rawDescData []byte
)

func file_proto_stages_kappa_proto_rawDescGZIP() []byte {
	file_proto_stages_kappa_proto_rawDescOnce.Do(func() {
		file_proto_stages_kappa_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_stages_kappa_proto_rawDesc), len(file_proto_stages_kappa_proto_rawDesc)))
	})
	return file_proto_stages_kappa_proto_rawDescData
}

var file_proto_stages_kappa_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_stages_kappa_proto_goTypes = []any{
	(*Kappa_1)(nil),      // 0: Kappa_1
	(*Kappa_2)(nil),      // 1: Kappa_2
	(*Kappa_3)(nil),      // 2: Kappa_3
	(*Kappa_1_Data)(nil), // 3: Kappa_1.Data
	(*Kappa_2_Data)(nil), // 4: Kappa_2.Data
	(*Kappa_3_Data)(nil), // 5: Kappa_3.Data
}
var file_proto_stages_kappa_proto_depIdxs = []int32{
	3, // 0: Kappa_1.data:type_name -> Kappa_1.Data
	4, // 1: Kappa_2.data:type_name -> Kappa_2.Data
	5, // 2: Kappa_3.data:type_name -> Kappa_3.Data
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_stages_kappa_proto_init() }
func file_proto_stages_kappa_proto_init() {
	if File_proto_stages_kappa_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_stages_kappa_proto_rawDesc), len(file_proto_stages_kappa_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_stages_kappa_proto_goTypes,
		DependencyIndexes: file_proto_stages_kappa_proto_depIdxs,
		MessageInfos:      file_proto_stages_kappa_proto_msgTypes,
	}.Build()
	File_proto_stages_kappa_proto = out.File
	file_proto_stages_kappa_proto_goTypes = nil
	file_proto_stages_kappa_proto_depIdxs = nil
}
