// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/stages/mu.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mu struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Mu_Data             `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mu) Reset() {
	*x = Mu{}
	mi := &file_proto_stages_mu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mu) ProtoMessage() {}

func (x *Mu) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stages_mu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mu.ProtoReflect.Descriptor instead.
func (*Mu) Descriptor() ([]byte, []int) {
	return file_proto_stages_mu_proto_rawDescGZIP(), []int{0}
}

func (x *Mu) GetData() []*Mu_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type Mu_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Revenue       uint64                 `protobuf:"varint,3,opt,name=revenue,proto3" json:"revenue,omitempty"`
	Budget        uint64                 `protobuf:"varint,4,opt,name=budget,proto3" json:"budget,omitempty"`
	Overview      string                 `protobuf:"bytes,5,opt,name=overview,proto3" json:"overview,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mu_Data) Reset() {
	*x = Mu_Data{}
	mi := &file_proto_stages_mu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mu_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mu_Data) ProtoMessage() {}

func (x *Mu_Data) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stages_mu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mu_Data.ProtoReflect.Descriptor instead.
func (*Mu_Data) Descriptor() ([]byte, []int) {
	return file_proto_stages_mu_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Mu_Data) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Mu_Data) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Mu_Data) GetRevenue() uint64 {
	if x != nil {
		return x.Revenue
	}
	return 0
}

func (x *Mu_Data) GetBudget() uint64 {
	if x != nil {
		return x.Budget
	}
	return 0
}

func (x *Mu_Data) GetOverview() string {
	if x != nil {
		return x.Overview
	}
	return ""
}

var File_proto_stages_mu_proto protoreflect.FileDescriptor

const file_proto_stages_mu_proto_rawDesc = "" +
	"\n" +
	"\x15proto/stages/mu.proto\"\x9e\x01\n" +
	"\x02Mu\x12\x1c\n" +
	"\x04data\x18\x01 \x03(\v2\b.Mu.DataR\x04data\x1az\n" +
	"\x04Data\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\arevenue\x18\x03 \x01(\x04R\arevenue\x12\x16\n" +
	"\x06budget\x18\x04 \x01(\x04R\x06budget\x12\x1a\n" +
	"\boverview\x18\x05 \x01(\tR\boverviewB\x1fZ\x1dcommon/communication/protocolb\x06proto3"

var (
	file_proto_stages_mu_proto_rawDescOnce sync.Once
	file_proto_stages_mu_proto_rawDescData []byte
)

func file_proto_stages_mu_proto_rawDescGZIP() []byte {
	file_proto_stages_mu_proto_rawDescOnce.Do(func() {
		file_proto_stages_mu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_stages_mu_proto_rawDesc), len(file_proto_stages_mu_proto_rawDesc)))
	})
	return file_proto_stages_mu_proto_rawDescData
}

var file_proto_stages_mu_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_stages_mu_proto_goTypes = []any{
	(*Mu)(nil),      // 0: Mu
	(*Mu_Data)(nil), // 1: Mu.Data
}
var file_proto_stages_mu_proto_depIdxs = []int32{
	1, // 0: Mu.data:type_name -> Mu.Data
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_stages_mu_proto_init() }
func file_proto_stages_mu_proto_init() {
	if File_proto_stages_mu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_stages_mu_proto_rawDesc), len(file_proto_stages_mu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_stages_mu_proto_goTypes,
		DependencyIndexes: file_proto_stages_mu_proto_depIdxs,
		MessageInfos:      file_proto_stages_mu_proto_msgTypes,
	}.Build()
	File_proto_stages_mu_proto = out.File
	file_proto_stages_mu_proto_goTypes = nil
	file_proto_stages_mu_proto_depIdxs = nil
}
