// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/eof/omegaEOF.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OmegaEOF struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *OmegaEOF_Data         `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OmegaEOF) Reset() {
	*x = OmegaEOF{}
	mi := &file_proto_eof_omegaEOF_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OmegaEOF) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OmegaEOF) ProtoMessage() {}

func (x *OmegaEOF) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eof_omegaEOF_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OmegaEOF.ProtoReflect.Descriptor instead.
func (*OmegaEOF) Descriptor() ([]byte, []int) {
	return file_proto_eof_omegaEOF_proto_rawDescGZIP(), []int{0}
}

func (x *OmegaEOF) GetData() *OmegaEOF_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type OmegaEOF_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         string                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	TasksCount    uint32                 `protobuf:"varint,2,opt,name=tasksCount,proto3" json:"tasksCount,omitempty"`
	EofType       string                 `protobuf:"bytes,3,opt,name=eofType,proto3" json:"eofType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OmegaEOF_Data) Reset() {
	*x = OmegaEOF_Data{}
	mi := &file_proto_eof_omegaEOF_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OmegaEOF_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OmegaEOF_Data) ProtoMessage() {}

func (x *OmegaEOF_Data) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eof_omegaEOF_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OmegaEOF_Data.ProtoReflect.Descriptor instead.
func (*OmegaEOF_Data) Descriptor() ([]byte, []int) {
	return file_proto_eof_omegaEOF_proto_rawDescGZIP(), []int{0, 0}
}

func (x *OmegaEOF_Data) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *OmegaEOF_Data) GetTasksCount() uint32 {
	if x != nil {
		return x.TasksCount
	}
	return 0
}

func (x *OmegaEOF_Data) GetEofType() string {
	if x != nil {
		return x.EofType
	}
	return ""
}

var File_proto_eof_omegaEOF_proto protoreflect.FileDescriptor

const file_proto_eof_omegaEOF_proto_rawDesc = "" +
	"\n" +
	"\x18proto/eof/omegaEOF.proto\"\x86\x01\n" +
	"\bOmegaEOF\x12\"\n" +
	"\x04data\x18\x01 \x01(\v2\x0e.OmegaEOF.DataR\x04data\x1aV\n" +
	"\x04Data\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\tR\x05stage\x12\x1e\n" +
	"\n" +
	"tasksCount\x18\x02 \x01(\rR\n" +
	"tasksCount\x12\x18\n" +
	"\aeofType\x18\x03 \x01(\tR\aeofTypeB\x1fZ\x1dcommon/communication/protocolb\x06proto3"

var (
	file_proto_eof_omegaEOF_proto_rawDescOnce sync.Once
	file_proto_eof_omegaEOF_proto_rawDescData []byte
)

func file_proto_eof_omegaEOF_proto_rawDescGZIP() []byte {
	file_proto_eof_omegaEOF_proto_rawDescOnce.Do(func() {
		file_proto_eof_omegaEOF_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_eof_omegaEOF_proto_rawDesc), len(file_proto_eof_omegaEOF_proto_rawDesc)))
	})
	return file_proto_eof_omegaEOF_proto_rawDescData
}

var file_proto_eof_omegaEOF_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_eof_omegaEOF_proto_goTypes = []any{
	(*OmegaEOF)(nil),      // 0: OmegaEOF
	(*OmegaEOF_Data)(nil), // 1: OmegaEOF.Data
}
var file_proto_eof_omegaEOF_proto_depIdxs = []int32{
	1, // 0: OmegaEOF.data:type_name -> OmegaEOF.Data
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_eof_omegaEOF_proto_init() }
func file_proto_eof_omegaEOF_proto_init() {
	if File_proto_eof_omegaEOF_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_eof_omegaEOF_proto_rawDesc), len(file_proto_eof_omegaEOF_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_eof_omegaEOF_proto_goTypes,
		DependencyIndexes: file_proto_eof_omegaEOF_proto_depIdxs,
		MessageInfos:      file_proto_eof_omegaEOF_proto_msgTypes,
	}.Build()
	File_proto_eof_omegaEOF_proto = out.File
	file_proto_eof_omegaEOF_proto_goTypes = nil
	file_proto_eof_omegaEOF_proto_depIdxs = nil
}
