// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/results/result5.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Result5 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Result5_Data        `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result5) Reset() {
	*x = Result5{}
	mi := &file_proto_results_result5_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result5) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result5) ProtoMessage() {}

func (x *Result5) ProtoReflect() protoreflect.Message {
	mi := &file_proto_results_result5_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result5.ProtoReflect.Descriptor instead.
func (*Result5) Descriptor() ([]byte, []int) {
	return file_proto_results_result5_proto_rawDescGZIP(), []int{0}
}

func (x *Result5) GetData() []*Result5_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type Result5_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sentiment     bool                   `protobuf:"varint,1,opt,name=sentiment,proto3" json:"sentiment,omitempty"`
	Ratio         float32                `protobuf:"fixed32,2,opt,name=ratio,proto3" json:"ratio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result5_Data) Reset() {
	*x = Result5_Data{}
	mi := &file_proto_results_result5_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result5_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result5_Data) ProtoMessage() {}

func (x *Result5_Data) ProtoReflect() protoreflect.Message {
	mi := &file_proto_results_result5_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result5_Data.ProtoReflect.Descriptor instead.
func (*Result5_Data) Descriptor() ([]byte, []int) {
	return file_proto_results_result5_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Result5_Data) GetSentiment() bool {
	if x != nil {
		return x.Sentiment
	}
	return false
}

func (x *Result5_Data) GetRatio() float32 {
	if x != nil {
		return x.Ratio
	}
	return 0
}

var File_proto_results_result5_proto protoreflect.FileDescriptor

const file_proto_results_result5_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/results/result5.proto\"h\n" +
	"\aResult5\x12!\n" +
	"\x04data\x18\x01 \x03(\v2\r.Result5.DataR\x04data\x1a:\n" +
	"\x04Data\x12\x1c\n" +
	"\tsentiment\x18\x01 \x01(\bR\tsentiment\x12\x14\n" +
	"\x05ratio\x18\x02 \x01(\x02R\x05ratioB\x1fZ\x1dcommon/communication/protocolb\x06proto3"

var (
	file_proto_results_result5_proto_rawDescOnce sync.Once
	file_proto_results_result5_proto_rawDescData []byte
)

func file_proto_results_result5_proto_rawDescGZIP() []byte {
	file_proto_results_result5_proto_rawDescOnce.Do(func() {
		file_proto_results_result5_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_results_result5_proto_rawDesc), len(file_proto_results_result5_proto_rawDesc)))
	})
	return file_proto_results_result5_proto_rawDescData
}

var file_proto_results_result5_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_results_result5_proto_goTypes = []any{
	(*Result5)(nil),      // 0: Result5
	(*Result5_Data)(nil), // 1: Result5.Data
}
var file_proto_results_result5_proto_depIdxs = []int32{
	1, // 0: Result5.data:type_name -> Result5.Data
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_results_result5_proto_init() }
func file_proto_results_result5_proto_init() {
	if File_proto_results_result5_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_results_result5_proto_rawDesc), len(file_proto_results_result5_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_results_result5_proto_goTypes,
		DependencyIndexes: file_proto_results_result5_proto_depIdxs,
		MessageInfos:      file_proto_results_result5_proto_msgTypes,
	}.Build()
	File_proto_results_result5_proto = out.File
	file_proto_results_result5_proto_goTypes = nil
	file_proto_results_result5_proto_depIdxs = nil
}
