// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/results/result3.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Result3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Result3_Data        `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result3) Reset() {
	*x = Result3{}
	mi := &file_proto_results_result3_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result3) ProtoMessage() {}

func (x *Result3) ProtoReflect() protoreflect.Message {
	mi := &file_proto_results_result3_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result3.ProtoReflect.Descriptor instead.
func (*Result3) Descriptor() ([]byte, []int) {
	return file_proto_results_result3_proto_rawDescGZIP(), []int{0}
}

func (x *Result3) GetData() []*Result3_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type Result3_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Rating        float32                `protobuf:"fixed32,4,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result3_Data) Reset() {
	*x = Result3_Data{}
	mi := &file_proto_results_result3_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result3_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result3_Data) ProtoMessage() {}

func (x *Result3_Data) ProtoReflect() protoreflect.Message {
	mi := &file_proto_results_result3_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result3_Data.ProtoReflect.Descriptor instead.
func (*Result3_Data) Descriptor() ([]byte, []int) {
	return file_proto_results_result3_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Result3_Data) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Result3_Data) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Result3_Data) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Result3_Data) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

var File_proto_results_result3_proto protoreflect.FileDescriptor

const file_proto_results_result3_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/results/result3.proto\"\x86\x01\n" +
	"\aResult3\x12!\n" +
	"\x04data\x18\x01 \x03(\v2\r.Result3.DataR\x04data\x1aX\n" +
	"\x04Data\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x02R\x06ratingB\x1fZ\x1dcommon/communication/protocolb\x06proto3"

var (
	file_proto_results_result3_proto_rawDescOnce sync.Once
	file_proto_results_result3_proto_rawDescData []byte
)

func file_proto_results_result3_proto_rawDescGZIP() []byte {
	file_proto_results_result3_proto_rawDescOnce.Do(func() {
		file_proto_results_result3_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_results_result3_proto_rawDesc), len(file_proto_results_result3_proto_rawDesc)))
	})
	return file_proto_results_result3_proto_rawDescData
}

var file_proto_results_result3_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_results_result3_proto_goTypes = []any{
	(*Result3)(nil),      // 0: Result3
	(*Result3_Data)(nil), // 1: Result3.Data
}
var file_proto_results_result3_proto_depIdxs = []int32{
	1, // 0: Result3.data:type_name -> Result3.Data
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_results_result3_proto_init() }
func file_proto_results_result3_proto_init() {
	if File_proto_results_result3_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_results_result3_proto_rawDesc), len(file_proto_results_result3_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_results_result3_proto_goTypes,
		DependencyIndexes: file_proto_results_result3_proto_depIdxs,
		MessageInfos:      file_proto_results_result3_proto_msgTypes,
	}.Build()
	File_proto_results_result3_proto = out.File
	file_proto_results_result3_proto_goTypes = nil
	file_proto_results_result3_proto_depIdxs = nil
}
