// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/results/result1.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Result1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Result1_Data        `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result1) Reset() {
	*x = Result1{}
	mi := &file_proto_results_result1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result1) ProtoMessage() {}

func (x *Result1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_results_result1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result1.ProtoReflect.Descriptor instead.
func (*Result1) Descriptor() ([]byte, []int) {
	return file_proto_results_result1_proto_rawDescGZIP(), []int{0}
}

func (x *Result1) GetData() []*Result1_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type Result1_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Genres        []string               `protobuf:"bytes,3,rep,name=genres,proto3" json:"genres,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result1_Data) Reset() {
	*x = Result1_Data{}
	mi := &file_proto_results_result1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result1_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result1_Data) ProtoMessage() {}

func (x *Result1_Data) ProtoReflect() protoreflect.Message {
	mi := &file_proto_results_result1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result1_Data.ProtoReflect.Descriptor instead.
func (*Result1_Data) Descriptor() ([]byte, []int) {
	return file_proto_results_result1_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Result1_Data) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Result1_Data) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Result1_Data) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

var File_proto_results_result1_proto protoreflect.FileDescriptor

const file_proto_results_result1_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/results/result1.proto\"r\n" +
	"\aResult1\x12!\n" +
	"\x04data\x18\x01 \x03(\v2\r.Result1.DataR\x04data\x1aD\n" +
	"\x04Data\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06genres\x18\x03 \x03(\tR\x06genresB\x1fZ\x1dcommon/communication/protocolb\x06proto3"

var (
	file_proto_results_result1_proto_rawDescOnce sync.Once
	file_proto_results_result1_proto_rawDescData []byte
)

func file_proto_results_result1_proto_rawDescGZIP() []byte {
	file_proto_results_result1_proto_rawDescOnce.Do(func() {
		file_proto_results_result1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_results_result1_proto_rawDesc), len(file_proto_results_result1_proto_rawDesc)))
	})
	return file_proto_results_result1_proto_rawDescData
}

var file_proto_results_result1_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_results_result1_proto_goTypes = []any{
	(*Result1)(nil),      // 0: Result1
	(*Result1_Data)(nil), // 1: Result1.Data
}
var file_proto_results_result1_proto_depIdxs = []int32{
	1, // 0: Result1.data:type_name -> Result1.Data
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_results_result1_proto_init() }
func file_proto_results_result1_proto_init() {
	if File_proto_results_result1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_results_result1_proto_rawDesc), len(file_proto_results_result1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_results_result1_proto_goTypes,
		DependencyIndexes: file_proto_results_result1_proto_depIdxs,
		MessageInfos:      file_proto_results_result1_proto_msgTypes,
	}.Build()
	File_proto_results_result1_proto = out.File
	file_proto_results_result1_proto_goTypes = nil
	file_proto_results_result1_proto_depIdxs = nil
}
