// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/eof/ringEOF.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FragmentIdentifier struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TaskNumber         uint32                 `protobuf:"varint,1,opt,name=taskNumber,proto3" json:"taskNumber,omitempty"`
	TaskFragmentNumber uint32                 `protobuf:"varint,2,opt,name=taskFragmentNumber,proto3" json:"taskFragmentNumber,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FragmentIdentifier) Reset() {
	*x = FragmentIdentifier{}
	mi := &file_proto_eof_ringEOF_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FragmentIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FragmentIdentifier) ProtoMessage() {}

func (x *FragmentIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eof_ringEOF_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FragmentIdentifier.ProtoReflect.Descriptor instead.
func (*FragmentIdentifier) Descriptor() ([]byte, []int) {
	return file_proto_eof_ringEOF_proto_rawDescGZIP(), []int{0}
}

func (x *FragmentIdentifier) GetTaskNumber() uint32 {
	if x != nil {
		return x.TaskNumber
	}
	return 0
}

func (x *FragmentIdentifier) GetTaskFragmentNumber() uint32 {
	if x != nil {
		return x.TaskFragmentNumber
	}
	return 0
}

type StageFragment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatorId     string                 `protobuf:"bytes,1,opt,name=creatorId,proto3" json:"creatorId,omitempty"`
	Start         *FragmentIdentifier    `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End           *FragmentIdentifier    `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	LastFragment  bool                   `protobuf:"varint,4,opt,name=lastFragment,proto3" json:"lastFragment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StageFragment) Reset() {
	*x = StageFragment{}
	mi := &file_proto_eof_ringEOF_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageFragment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageFragment) ProtoMessage() {}

func (x *StageFragment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eof_ringEOF_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageFragment.ProtoReflect.Descriptor instead.
func (*StageFragment) Descriptor() ([]byte, []int) {
	return file_proto_eof_ringEOF_proto_rawDescGZIP(), []int{1}
}

func (x *StageFragment) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *StageFragment) GetStart() *FragmentIdentifier {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *StageFragment) GetEnd() *FragmentIdentifier {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *StageFragment) GetLastFragment() bool {
	if x != nil {
		return x.LastFragment
	}
	return false
}

type TaskCountByWorker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=workerId,proto3" json:"workerId,omitempty"`
	TaskCount     uint32                 `protobuf:"varint,2,opt,name=taskCount,proto3" json:"taskCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskCountByWorker) Reset() {
	*x = TaskCountByWorker{}
	mi := &file_proto_eof_ringEOF_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCountByWorker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCountByWorker) ProtoMessage() {}

func (x *TaskCountByWorker) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eof_ringEOF_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCountByWorker.ProtoReflect.Descriptor instead.
func (*TaskCountByWorker) Descriptor() ([]byte, []int) {
	return file_proto_eof_ringEOF_proto_rawDescGZIP(), []int{2}
}

func (x *TaskCountByWorker) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *TaskCountByWorker) GetTaskCount() uint32 {
	if x != nil {
		return x.TaskCount
	}
	return 0
}

type RingEOF struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Stage                      string                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	EofType                    string                 `protobuf:"bytes,2,opt,name=eofType,proto3" json:"eofType,omitempty"`
	CreatorId                  string                 `protobuf:"bytes,3,opt,name=creatorId,proto3" json:"creatorId,omitempty"`
	ReadyId                    string                 `protobuf:"bytes,4,opt,name=readyId,proto3" json:"readyId,omitempty"`
	TasksCount                 uint32                 `protobuf:"varint,5,opt,name=tasksCount,proto3" json:"tasksCount,omitempty"`
	RoundNumber                uint32                 `protobuf:"varint,6,opt,name=roundNumber,proto3" json:"roundNumber,omitempty"`
	StageFragmentes            []*StageFragment       `protobuf:"bytes,7,rep,name=stageFragmentes,proto3" json:"stageFragmentes,omitempty"`
	NextStageTaskCountByWorker []*TaskCountByWorker   `protobuf:"bytes,8,rep,name=nextStageTaskCountByWorker,proto3" json:"nextStageTaskCountByWorker,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *RingEOF) Reset() {
	*x = RingEOF{}
	mi := &file_proto_eof_ringEOF_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RingEOF) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RingEOF) ProtoMessage() {}

func (x *RingEOF) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eof_ringEOF_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RingEOF.ProtoReflect.Descriptor instead.
func (*RingEOF) Descriptor() ([]byte, []int) {
	return file_proto_eof_ringEOF_proto_rawDescGZIP(), []int{3}
}

func (x *RingEOF) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *RingEOF) GetEofType() string {
	if x != nil {
		return x.EofType
	}
	return ""
}

func (x *RingEOF) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *RingEOF) GetReadyId() string {
	if x != nil {
		return x.ReadyId
	}
	return ""
}

func (x *RingEOF) GetTasksCount() uint32 {
	if x != nil {
		return x.TasksCount
	}
	return 0
}

func (x *RingEOF) GetRoundNumber() uint32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

func (x *RingEOF) GetStageFragmentes() []*StageFragment {
	if x != nil {
		return x.StageFragmentes
	}
	return nil
}

func (x *RingEOF) GetNextStageTaskCountByWorker() []*TaskCountByWorker {
	if x != nil {
		return x.NextStageTaskCountByWorker
	}
	return nil
}

var File_proto_eof_ringEOF_proto protoreflect.FileDescriptor

const file_proto_eof_ringEOF_proto_rawDesc = "" +
	"\n" +
	"\x17proto/eof/ringEOF.proto\"d\n" +
	"\x12FragmentIdentifier\x12\x1e\n" +
	"\n" +
	"taskNumber\x18\x01 \x01(\rR\n" +
	"taskNumber\x12.\n" +
	"\x12taskFragmentNumber\x18\x02 \x01(\rR\x12taskFragmentNumber\"\xa3\x01\n" +
	"\rStageFragment\x12\x1c\n" +
	"\tcreatorId\x18\x01 \x01(\tR\tcreatorId\x12)\n" +
	"\x05start\x18\x02 \x01(\v2\x13.FragmentIdentifierR\x05start\x12%\n" +
	"\x03end\x18\x03 \x01(\v2\x13.FragmentIdentifierR\x03end\x12\"\n" +
	"\flastFragment\x18\x04 \x01(\bR\flastFragment\"M\n" +
	"\x11TaskCountByWorker\x12\x1a\n" +
	"\bworkerId\x18\x01 \x01(\tR\bworkerId\x12\x1c\n" +
	"\ttaskCount\x18\x02 \x01(\rR\ttaskCount\"\xc1\x02\n" +
	"\aRingEOF\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\tR\x05stage\x12\x18\n" +
	"\aeofType\x18\x02 \x01(\tR\aeofType\x12\x1c\n" +
	"\tcreatorId\x18\x03 \x01(\tR\tcreatorId\x12\x18\n" +
	"\areadyId\x18\x04 \x01(\tR\areadyId\x12\x1e\n" +
	"\n" +
	"tasksCount\x18\x05 \x01(\rR\n" +
	"tasksCount\x12 \n" +
	"\vroundNumber\x18\x06 \x01(\rR\vroundNumber\x128\n" +
	"\x0fstageFragmentes\x18\a \x03(\v2\x0e.StageFragmentR\x0fstageFragmentes\x12R\n" +
	"\x1anextStageTaskCountByWorker\x18\b \x03(\v2\x12.TaskCountByWorkerR\x1anextStageTaskCountByWorkerB\x1fZ\x1dcommon/communication/protocolb\x06proto3"

var (
	file_proto_eof_ringEOF_proto_rawDescOnce sync.Once
	file_proto_eof_ringEOF_proto_rawDescData []byte
)

func file_proto_eof_ringEOF_proto_rawDescGZIP() []byte {
	file_proto_eof_ringEOF_proto_rawDescOnce.Do(func() {
		file_proto_eof_ringEOF_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_eof_ringEOF_proto_rawDesc), len(file_proto_eof_ringEOF_proto_rawDesc)))
	})
	return file_proto_eof_ringEOF_proto_rawDescData
}

var file_proto_eof_ringEOF_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_eof_ringEOF_proto_goTypes = []any{
	(*FragmentIdentifier)(nil), // 0: FragmentIdentifier
	(*StageFragment)(nil),      // 1: StageFragment
	(*TaskCountByWorker)(nil),  // 2: TaskCountByWorker
	(*RingEOF)(nil),            // 3: RingEOF
}
var file_proto_eof_ringEOF_proto_depIdxs = []int32{
	0, // 0: StageFragment.start:type_name -> FragmentIdentifier
	0, // 1: StageFragment.end:type_name -> FragmentIdentifier
	1, // 2: RingEOF.stageFragmentes:type_name -> StageFragment
	2, // 3: RingEOF.nextStageTaskCountByWorker:type_name -> TaskCountByWorker
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_eof_ringEOF_proto_init() }
func file_proto_eof_ringEOF_proto_init() {
	if File_proto_eof_ringEOF_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_eof_ringEOF_proto_rawDesc), len(file_proto_eof_ringEOF_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_eof_ringEOF_proto_goTypes,
		DependencyIndexes: file_proto_eof_ringEOF_proto_depIdxs,
		MessageInfos:      file_proto_eof_ringEOF_proto_msgTypes,
	}.Build()
	File_proto_eof_ringEOF_proto = out.File
	file_proto_eof_ringEOF_proto_goTypes = nil
	file_proto_eof_ringEOF_proto_depIdxs = nil
}
