// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/task.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskIdentifier struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CreatorId          string                 `protobuf:"bytes,1,opt,name=creatorId,proto3" json:"creatorId,omitempty"`
	TaskNumber         uint32                 `protobuf:"varint,2,opt,name=taskNumber,proto3" json:"taskNumber,omitempty"`
	TaskFragmentNumber uint32                 `protobuf:"varint,3,opt,name=taskFragmentNumber,proto3" json:"taskFragmentNumber,omitempty"`
	LastFragment       bool                   `protobuf:"varint,4,opt,name=lastFragment,proto3" json:"lastFragment,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TaskIdentifier) Reset() {
	*x = TaskIdentifier{}
	mi := &file_proto_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskIdentifier) ProtoMessage() {}

func (x *TaskIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskIdentifier.ProtoReflect.Descriptor instead.
func (*TaskIdentifier) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{0}
}

func (x *TaskIdentifier) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *TaskIdentifier) GetTaskNumber() uint32 {
	if x != nil {
		return x.TaskNumber
	}
	return 0
}

func (x *TaskIdentifier) GetTaskFragmentNumber() uint32 {
	if x != nil {
		return x.TaskFragmentNumber
	}
	return 0
}

func (x *TaskIdentifier) GetLastFragment() bool {
	if x != nil {
		return x.LastFragment
	}
	return false
}

type Task struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Stage:
	//
	//	*Task_Alpha
	//	*Task_Beta
	//	*Task_Gamma
	//	*Task_Delta_1
	//	*Task_Delta_2
	//	*Task_Delta_3
	//	*Task_Epsilon
	//	*Task_Zeta
	//	*Task_Eta_1
	//	*Task_Eta_2
	//	*Task_Eta_3
	//	*Task_Theta
	//	*Task_Iota
	//	*Task_Kappa_1
	//	*Task_Kappa_2
	//	*Task_Kappa_3
	//	*Task_Lambda
	//	*Task_Mu
	//	*Task_Nu_1
	//	*Task_Nu_2
	//	*Task_Nu_3
	//	*Task_Result1
	//	*Task_Result2
	//	*Task_Result3
	//	*Task_Result4
	//	*Task_Result5
	//	*Task_OmegaEOF
	//	*Task_RingEOF
	Stage          isTask_Stage    `protobuf_oneof:"Stage"`
	ClientId       string          `protobuf:"bytes,29,opt,name=clientId,proto3" json:"clientId,omitempty"`
	TaskIdentifier *TaskIdentifier `protobuf:"bytes,30,opt,name=taskIdentifier,proto3" json:"taskIdentifier,omitempty"`
	TableType      string          `protobuf:"bytes,31,opt,name=tableType,proto3" json:"tableType,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{1}
}

func (x *Task) GetStage() isTask_Stage {
	if x != nil {
		return x.Stage
	}
	return nil
}

func (x *Task) GetAlpha() *Alpha {
	if x != nil {
		if x, ok := x.Stage.(*Task_Alpha); ok {
			return x.Alpha
		}
	}
	return nil
}

func (x *Task) GetBeta() *Beta {
	if x != nil {
		if x, ok := x.Stage.(*Task_Beta); ok {
			return x.Beta
		}
	}
	return nil
}

func (x *Task) GetGamma() *Gamma {
	if x != nil {
		if x, ok := x.Stage.(*Task_Gamma); ok {
			return x.Gamma
		}
	}
	return nil
}

func (x *Task) GetDelta_1() *Delta_1 {
	if x != nil {
		if x, ok := x.Stage.(*Task_Delta_1); ok {
			return x.Delta_1
		}
	}
	return nil
}

func (x *Task) GetDelta_2() *Delta_2 {
	if x != nil {
		if x, ok := x.Stage.(*Task_Delta_2); ok {
			return x.Delta_2
		}
	}
	return nil
}

func (x *Task) GetDelta_3() *Delta_3 {
	if x != nil {
		if x, ok := x.Stage.(*Task_Delta_3); ok {
			return x.Delta_3
		}
	}
	return nil
}

func (x *Task) GetEpsilon() *Epsilon {
	if x != nil {
		if x, ok := x.Stage.(*Task_Epsilon); ok {
			return x.Epsilon
		}
	}
	return nil
}

func (x *Task) GetZeta() *Zeta {
	if x != nil {
		if x, ok := x.Stage.(*Task_Zeta); ok {
			return x.Zeta
		}
	}
	return nil
}

func (x *Task) GetEta_1() *Eta_1 {
	if x != nil {
		if x, ok := x.Stage.(*Task_Eta_1); ok {
			return x.Eta_1
		}
	}
	return nil
}

func (x *Task) GetEta_2() *Eta_2 {
	if x != nil {
		if x, ok := x.Stage.(*Task_Eta_2); ok {
			return x.Eta_2
		}
	}
	return nil
}

func (x *Task) GetEta_3() *Eta_3 {
	if x != nil {
		if x, ok := x.Stage.(*Task_Eta_3); ok {
			return x.Eta_3
		}
	}
	return nil
}

func (x *Task) GetTheta() *Theta {
	if x != nil {
		if x, ok := x.Stage.(*Task_Theta); ok {
			return x.Theta
		}
	}
	return nil
}

func (x *Task) GetIota() *Iota {
	if x != nil {
		if x, ok := x.Stage.(*Task_Iota); ok {
			return x.Iota
		}
	}
	return nil
}

func (x *Task) GetKappa_1() *Kappa_1 {
	if x != nil {
		if x, ok := x.Stage.(*Task_Kappa_1); ok {
			return x.Kappa_1
		}
	}
	return nil
}

func (x *Task) GetKappa_2() *Kappa_2 {
	if x != nil {
		if x, ok := x.Stage.(*Task_Kappa_2); ok {
			return x.Kappa_2
		}
	}
	return nil
}

func (x *Task) GetKappa_3() *Kappa_3 {
	if x != nil {
		if x, ok := x.Stage.(*Task_Kappa_3); ok {
			return x.Kappa_3
		}
	}
	return nil
}

func (x *Task) GetLambda() *Lambda {
	if x != nil {
		if x, ok := x.Stage.(*Task_Lambda); ok {
			return x.Lambda
		}
	}
	return nil
}

func (x *Task) GetMu() *Mu {
	if x != nil {
		if x, ok := x.Stage.(*Task_Mu); ok {
			return x.Mu
		}
	}
	return nil
}

func (x *Task) GetNu_1() *Nu_1 {
	if x != nil {
		if x, ok := x.Stage.(*Task_Nu_1); ok {
			return x.Nu_1
		}
	}
	return nil
}

func (x *Task) GetNu_2() *Nu_2 {
	if x != nil {
		if x, ok := x.Stage.(*Task_Nu_2); ok {
			return x.Nu_2
		}
	}
	return nil
}

func (x *Task) GetNu_3() *Nu_3 {
	if x != nil {
		if x, ok := x.Stage.(*Task_Nu_3); ok {
			return x.Nu_3
		}
	}
	return nil
}

func (x *Task) GetResult1() *Result1 {
	if x != nil {
		if x, ok := x.Stage.(*Task_Result1); ok {
			return x.Result1
		}
	}
	return nil
}

func (x *Task) GetResult2() *Result2 {
	if x != nil {
		if x, ok := x.Stage.(*Task_Result2); ok {
			return x.Result2
		}
	}
	return nil
}

func (x *Task) GetResult3() *Result3 {
	if x != nil {
		if x, ok := x.Stage.(*Task_Result3); ok {
			return x.Result3
		}
	}
	return nil
}

func (x *Task) GetResult4() *Result4 {
	if x != nil {
		if x, ok := x.Stage.(*Task_Result4); ok {
			return x.Result4
		}
	}
	return nil
}

func (x *Task) GetResult5() *Result5 {
	if x != nil {
		if x, ok := x.Stage.(*Task_Result5); ok {
			return x.Result5
		}
	}
	return nil
}

func (x *Task) GetOmegaEOF() *OmegaEOF {
	if x != nil {
		if x, ok := x.Stage.(*Task_OmegaEOF); ok {
			return x.OmegaEOF
		}
	}
	return nil
}

func (x *Task) GetRingEOF() *RingEOF {
	if x != nil {
		if x, ok := x.Stage.(*Task_RingEOF); ok {
			return x.RingEOF
		}
	}
	return nil
}

func (x *Task) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Task) GetTaskIdentifier() *TaskIdentifier {
	if x != nil {
		return x.TaskIdentifier
	}
	return nil
}

func (x *Task) GetTableType() string {
	if x != nil {
		return x.TableType
	}
	return ""
}

type isTask_Stage interface {
	isTask_Stage()
}

type Task_Alpha struct {
	Alpha *Alpha `protobuf:"bytes,1,opt,name=alpha,proto3,oneof"`
}

type Task_Beta struct {
	Beta *Beta `protobuf:"bytes,2,opt,name=beta,proto3,oneof"`
}

type Task_Gamma struct {
	Gamma *Gamma `protobuf:"bytes,3,opt,name=gamma,proto3,oneof"`
}

type Task_Delta_1 struct {
	Delta_1 *Delta_1 `protobuf:"bytes,4,opt,name=delta_1,json=delta1,proto3,oneof"`
}

type Task_Delta_2 struct {
	Delta_2 *Delta_2 `protobuf:"bytes,5,opt,name=delta_2,json=delta2,proto3,oneof"`
}

type Task_Delta_3 struct {
	Delta_3 *Delta_3 `protobuf:"bytes,6,opt,name=delta_3,json=delta3,proto3,oneof"`
}

type Task_Epsilon struct {
	Epsilon *Epsilon `protobuf:"bytes,7,opt,name=epsilon,proto3,oneof"`
}

type Task_Zeta struct {
	Zeta *Zeta `protobuf:"bytes,8,opt,name=zeta,proto3,oneof"`
}

type Task_Eta_1 struct {
	Eta_1 *Eta_1 `protobuf:"bytes,9,opt,name=eta_1,json=eta1,proto3,oneof"`
}

type Task_Eta_2 struct {
	Eta_2 *Eta_2 `protobuf:"bytes,10,opt,name=eta_2,json=eta2,proto3,oneof"`
}

type Task_Eta_3 struct {
	Eta_3 *Eta_3 `protobuf:"bytes,11,opt,name=eta_3,json=eta3,proto3,oneof"`
}

type Task_Theta struct {
	Theta *Theta `protobuf:"bytes,12,opt,name=theta,proto3,oneof"`
}

type Task_Iota struct {
	Iota *Iota `protobuf:"bytes,13,opt,name=iota,proto3,oneof"`
}

type Task_Kappa_1 struct {
	Kappa_1 *Kappa_1 `protobuf:"bytes,14,opt,name=kappa_1,json=kappa1,proto3,oneof"`
}

type Task_Kappa_2 struct {
	Kappa_2 *Kappa_2 `protobuf:"bytes,15,opt,name=kappa_2,json=kappa2,proto3,oneof"`
}

type Task_Kappa_3 struct {
	Kappa_3 *Kappa_3 `protobuf:"bytes,16,opt,name=kappa_3,json=kappa3,proto3,oneof"`
}

type Task_Lambda struct {
	Lambda *Lambda `protobuf:"bytes,17,opt,name=lambda,proto3,oneof"`
}

type Task_Mu struct {
	Mu *Mu `protobuf:"bytes,18,opt,name=mu,proto3,oneof"`
}

type Task_Nu_1 struct {
	Nu_1 *Nu_1 `protobuf:"bytes,19,opt,name=nu_1,json=nu1,proto3,oneof"`
}

type Task_Nu_2 struct {
	Nu_2 *Nu_2 `protobuf:"bytes,20,opt,name=nu_2,json=nu2,proto3,oneof"`
}

type Task_Nu_3 struct {
	Nu_3 *Nu_3 `protobuf:"bytes,21,opt,name=nu_3,json=nu3,proto3,oneof"`
}

type Task_Result1 struct {
	Result1 *Result1 `protobuf:"bytes,22,opt,name=result1,proto3,oneof"`
}

type Task_Result2 struct {
	Result2 *Result2 `protobuf:"bytes,23,opt,name=result2,proto3,oneof"`
}

type Task_Result3 struct {
	Result3 *Result3 `protobuf:"bytes,24,opt,name=result3,proto3,oneof"`
}

type Task_Result4 struct {
	Result4 *Result4 `protobuf:"bytes,25,opt,name=result4,proto3,oneof"`
}

type Task_Result5 struct {
	Result5 *Result5 `protobuf:"bytes,26,opt,name=result5,proto3,oneof"`
}

type Task_OmegaEOF struct {
	OmegaEOF *OmegaEOF `protobuf:"bytes,27,opt,name=omegaEOF,proto3,oneof"`
}

type Task_RingEOF struct {
	RingEOF *RingEOF `protobuf:"bytes,28,opt,name=ringEOF,proto3,oneof"`
}

func (*Task_Alpha) isTask_Stage() {}

func (*Task_Beta) isTask_Stage() {}

func (*Task_Gamma) isTask_Stage() {}

func (*Task_Delta_1) isTask_Stage() {}

func (*Task_Delta_2) isTask_Stage() {}

func (*Task_Delta_3) isTask_Stage() {}

func (*Task_Epsilon) isTask_Stage() {}

func (*Task_Zeta) isTask_Stage() {}

func (*Task_Eta_1) isTask_Stage() {}

func (*Task_Eta_2) isTask_Stage() {}

func (*Task_Eta_3) isTask_Stage() {}

func (*Task_Theta) isTask_Stage() {}

func (*Task_Iota) isTask_Stage() {}

func (*Task_Kappa_1) isTask_Stage() {}

func (*Task_Kappa_2) isTask_Stage() {}

func (*Task_Kappa_3) isTask_Stage() {}

func (*Task_Lambda) isTask_Stage() {}

func (*Task_Mu) isTask_Stage() {}

func (*Task_Nu_1) isTask_Stage() {}

func (*Task_Nu_2) isTask_Stage() {}

func (*Task_Nu_3) isTask_Stage() {}

func (*Task_Result1) isTask_Stage() {}

func (*Task_Result2) isTask_Stage() {}

func (*Task_Result3) isTask_Stage() {}

func (*Task_Result4) isTask_Stage() {}

func (*Task_Result5) isTask_Stage() {}

func (*Task_OmegaEOF) isTask_Stage() {}

func (*Task_RingEOF) isTask_Stage() {}

var File_proto_task_proto protoreflect.FileDescriptor

const file_proto_task_proto_rawDesc = "" +
	"\n" +
	"\x10proto/task.proto\x1a\x18proto/stages/alpha.proto\x1a\x17proto/stages/beta.proto\x1a\x18proto/stages/gamma.proto\x1a\x18proto/stages/delta.proto\x1a\x1aproto/stages/epsilon.proto\x1a\x17proto/stages/zeta.proto\x1a\x16proto/stages/eta.proto\x1a\x18proto/stages/theta.proto\x1a\x17proto/stages/iota.proto\x1a\x18proto/stages/kappa.proto\x1a\x19proto/stages/lambda.proto\x1a\x15proto/stages/mu.proto\x1a\x15proto/stages/nu.proto\x1a\x1bproto/results/result1.proto\x1a\x1bproto/results/result2.proto\x1a\x1bproto/results/result3.proto\x1a\x1bproto/results/result4.proto\x1a\x1bproto/results/result5.proto\x1a\x18proto/eof/omegaEOF.proto\x1a\x17proto/eof/ringEOF.proto\"\xa2\x01\n" +
	"\x0eTaskIdentifier\x12\x1c\n" +
	"\tcreatorId\x18\x01 \x01(\tR\tcreatorId\x12\x1e\n" +
	"\n" +
	"taskNumber\x18\x02 \x01(\rR\n" +
	"taskNumber\x12.\n" +
	"\x12taskFragmentNumber\x18\x03 \x01(\rR\x12taskFragmentNumber\x12\"\n" +
	"\flastFragment\x18\x04 \x01(\bR\flastFragment\"\xb5\b\n" +
	"\x04Task\x12\x1e\n" +
	"\x05alpha\x18\x01 \x01(\v2\x06.AlphaH\x00R\x05alpha\x12\x1b\n" +
	"\x04beta\x18\x02 \x01(\v2\x05.BetaH\x00R\x04beta\x12\x1e\n" +
	"\x05gamma\x18\x03 \x01(\v2\x06.GammaH\x00R\x05gamma\x12#\n" +
	"\adelta_1\x18\x04 \x01(\v2\b.Delta_1H\x00R\x06delta1\x12#\n" +
	"\adelta_2\x18\x05 \x01(\v2\b.Delta_2H\x00R\x06delta2\x12#\n" +
	"\adelta_3\x18\x06 \x01(\v2\b.Delta_3H\x00R\x06delta3\x12$\n" +
	"\aepsilon\x18\a \x01(\v2\b.EpsilonH\x00R\aepsilon\x12\x1b\n" +
	"\x04zeta\x18\b \x01(\v2\x05.ZetaH\x00R\x04zeta\x12\x1d\n" +
	"\x05eta_1\x18\t \x01(\v2\x06.Eta_1H\x00R\x04eta1\x12\x1d\n" +
	"\x05eta_2\x18\n" +
	" \x01(\v2\x06.Eta_2H\x00R\x04eta2\x12\x1d\n" +
	"\x05eta_3\x18\v \x01(\v2\x06.Eta_3H\x00R\x04eta3\x12\x1e\n" +
	"\x05theta\x18\f \x01(\v2\x06.ThetaH\x00R\x05theta\x12\x1b\n" +
	"\x04iota\x18\r \x01(\v2\x05.IotaH\x00R\x04iota\x12#\n" +
	"\akappa_1\x18\x0e \x01(\v2\b.Kappa_1H\x00R\x06kappa1\x12#\n" +
	"\akappa_2\x18\x0f \x01(\v2\b.Kappa_2H\x00R\x06kappa2\x12#\n" +
	"\akappa_3\x18\x10 \x01(\v2\b.Kappa_3H\x00R\x06kappa3\x12!\n" +
	"\x06lambda\x18\x11 \x01(\v2\a.LambdaH\x00R\x06lambda\x12\x15\n" +
	"\x02mu\x18\x12 \x01(\v2\x03.MuH\x00R\x02mu\x12\x1a\n" +
	"\x04nu_1\x18\x13 \x01(\v2\x05.Nu_1H\x00R\x03nu1\x12\x1a\n" +
	"\x04nu_2\x18\x14 \x01(\v2\x05.Nu_2H\x00R\x03nu2\x12\x1a\n" +
	"\x04nu_3\x18\x15 \x01(\v2\x05.Nu_3H\x00R\x03nu3\x12$\n" +
	"\aresult1\x18\x16 \x01(\v2\b.Result1H\x00R\aresult1\x12$\n" +
	"\aresult2\x18\x17 \x01(\v2\b.Result2H\x00R\aresult2\x12$\n" +
	"\aresult3\x18\x18 \x01(\v2\b.Result3H\x00R\aresult3\x12$\n" +
	"\aresult4\x18\x19 \x01(\v2\b.Result4H\x00R\aresult4\x12$\n" +
	"\aresult5\x18\x1a \x01(\v2\b.Result5H\x00R\aresult5\x12'\n" +
	"\bomegaEOF\x18\x1b \x01(\v2\t.OmegaEOFH\x00R\bomegaEOF\x12$\n" +
	"\aringEOF\x18\x1c \x01(\v2\b.RingEOFH\x00R\aringEOF\x12\x1a\n" +
	"\bclientId\x18\x1d \x01(\tR\bclientId\x127\n" +
	"\x0etaskIdentifier\x18\x1e \x01(\v2\x0f.TaskIdentifierR\x0etaskIdentifier\x12\x1c\n" +
	"\ttableType\x18\x1f \x01(\tR\ttableTypeB\a\n" +
	"\x05StageB\x1fZ\x1dcommon/communication/protocolb\x06proto3"

var (
	file_proto_task_proto_rawDescOnce sync.Once
	file_proto_task_proto_rawDescData []byte
)

func file_proto_task_proto_rawDescGZIP() []byte {
	file_proto_task_proto_rawDescOnce.Do(func() {
		file_proto_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_task_proto_rawDesc), len(file_proto_task_proto_rawDesc)))
	})
	return file_proto_task_proto_rawDescData
}

var file_proto_task_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_task_proto_goTypes = []any{
	(*TaskIdentifier)(nil), // 0: TaskIdentifier
	(*Task)(nil),           // 1: Task
	(*Alpha)(nil),          // 2: Alpha
	(*Beta)(nil),           // 3: Beta
	(*Gamma)(nil),          // 4: Gamma
	(*Delta_1)(nil),        // 5: Delta_1
	(*Delta_2)(nil),        // 6: Delta_2
	(*Delta_3)(nil),        // 7: Delta_3
	(*Epsilon)(nil),        // 8: Epsilon
	(*Zeta)(nil),           // 9: Zeta
	(*Eta_1)(nil),          // 10: Eta_1
	(*Eta_2)(nil),          // 11: Eta_2
	(*Eta_3)(nil),          // 12: Eta_3
	(*Theta)(nil),          // 13: Theta
	(*Iota)(nil),           // 14: Iota
	(*Kappa_1)(nil),        // 15: Kappa_1
	(*Kappa_2)(nil),        // 16: Kappa_2
	(*Kappa_3)(nil),        // 17: Kappa_3
	(*Lambda)(nil),         // 18: Lambda
	(*Mu)(nil),             // 19: Mu
	(*Nu_1)(nil),           // 20: Nu_1
	(*Nu_2)(nil),           // 21: Nu_2
	(*Nu_3)(nil),           // 22: Nu_3
	(*Result1)(nil),        // 23: Result1
	(*Result2)(nil),        // 24: Result2
	(*Result3)(nil),        // 25: Result3
	(*Result4)(nil),        // 26: Result4
	(*Result5)(nil),        // 27: Result5
	(*OmegaEOF)(nil),       // 28: OmegaEOF
	(*RingEOF)(nil),        // 29: RingEOF
}
var file_proto_task_proto_depIdxs = []int32{
	2,  // 0: Task.alpha:type_name -> Alpha
	3,  // 1: Task.beta:type_name -> Beta
	4,  // 2: Task.gamma:type_name -> Gamma
	5,  // 3: Task.delta_1:type_name -> Delta_1
	6,  // 4: Task.delta_2:type_name -> Delta_2
	7,  // 5: Task.delta_3:type_name -> Delta_3
	8,  // 6: Task.epsilon:type_name -> Epsilon
	9,  // 7: Task.zeta:type_name -> Zeta
	10, // 8: Task.eta_1:type_name -> Eta_1
	11, // 9: Task.eta_2:type_name -> Eta_2
	12, // 10: Task.eta_3:type_name -> Eta_3
	13, // 11: Task.theta:type_name -> Theta
	14, // 12: Task.iota:type_name -> Iota
	15, // 13: Task.kappa_1:type_name -> Kappa_1
	16, // 14: Task.kappa_2:type_name -> Kappa_2
	17, // 15: Task.kappa_3:type_name -> Kappa_3
	18, // 16: Task.lambda:type_name -> Lambda
	19, // 17: Task.mu:type_name -> Mu
	20, // 18: Task.nu_1:type_name -> Nu_1
	21, // 19: Task.nu_2:type_name -> Nu_2
	22, // 20: Task.nu_3:type_name -> Nu_3
	23, // 21: Task.result1:type_name -> Result1
	24, // 22: Task.result2:type_name -> Result2
	25, // 23: Task.result3:type_name -> Result3
	26, // 24: Task.result4:type_name -> Result4
	27, // 25: Task.result5:type_name -> Result5
	28, // 26: Task.omegaEOF:type_name -> OmegaEOF
	29, // 27: Task.ringEOF:type_name -> RingEOF
	0,  // 28: Task.taskIdentifier:type_name -> TaskIdentifier
	29, // [29:29] is the sub-list for method output_type
	29, // [29:29] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_proto_task_proto_init() }
func file_proto_task_proto_init() {
	if File_proto_task_proto != nil {
		return
	}
	file_proto_stages_alpha_proto_init()
	file_proto_stages_beta_proto_init()
	file_proto_stages_gamma_proto_init()
	file_proto_stages_delta_proto_init()
	file_proto_stages_epsilon_proto_init()
	file_proto_stages_zeta_proto_init()
	file_proto_stages_eta_proto_init()
	file_proto_stages_theta_proto_init()
	file_proto_stages_iota_proto_init()
	file_proto_stages_kappa_proto_init()
	file_proto_stages_lambda_proto_init()
	file_proto_stages_mu_proto_init()
	file_proto_stages_nu_proto_init()
	file_proto_results_result1_proto_init()
	file_proto_results_result2_proto_init()
	file_proto_results_result3_proto_init()
	file_proto_results_result4_proto_init()
	file_proto_results_result5_proto_init()
	file_proto_eof_omegaEOF_proto_init()
	file_proto_eof_ringEOF_proto_init()
	file_proto_task_proto_msgTypes[1].OneofWrappers = []any{
		(*Task_Alpha)(nil),
		(*Task_Beta)(nil),
		(*Task_Gamma)(nil),
		(*Task_Delta_1)(nil),
		(*Task_Delta_2)(nil),
		(*Task_Delta_3)(nil),
		(*Task_Epsilon)(nil),
		(*Task_Zeta)(nil),
		(*Task_Eta_1)(nil),
		(*Task_Eta_2)(nil),
		(*Task_Eta_3)(nil),
		(*Task_Theta)(nil),
		(*Task_Iota)(nil),
		(*Task_Kappa_1)(nil),
		(*Task_Kappa_2)(nil),
		(*Task_Kappa_3)(nil),
		(*Task_Lambda)(nil),
		(*Task_Mu)(nil),
		(*Task_Nu_1)(nil),
		(*Task_Nu_2)(nil),
		(*Task_Nu_3)(nil),
		(*Task_Result1)(nil),
		(*Task_Result2)(nil),
		(*Task_Result3)(nil),
		(*Task_Result4)(nil),
		(*Task_Result5)(nil),
		(*Task_OmegaEOF)(nil),
		(*Task_RingEOF)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_task_proto_rawDesc), len(file_proto_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_task_proto_goTypes,
		DependencyIndexes: file_proto_task_proto_depIdxs,
		MessageInfos:      file_proto_task_proto_msgTypes,
	}.Build()
	File_proto_task_proto = out.File
	file_proto_task_proto_goTypes = nil
	file_proto_task_proto_depIdxs = nil
}
