// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/stages/theta.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Theta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Theta_Data          `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Theta) Reset() {
	*x = Theta{}
	mi := &file_proto_stages_theta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Theta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Theta) ProtoMessage() {}

func (x *Theta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stages_theta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Theta.ProtoReflect.Descriptor instead.
func (*Theta) Descriptor() ([]byte, []int) {
	return file_proto_stages_theta_proto_rawDescGZIP(), []int{0}
}

func (x *Theta) GetData() []*Theta_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type Theta_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	AvgRating     float32                `protobuf:"fixed32,3,opt,name=avgRating,proto3" json:"avgRating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Theta_Data) Reset() {
	*x = Theta_Data{}
	mi := &file_proto_stages_theta_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Theta_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Theta_Data) ProtoMessage() {}

func (x *Theta_Data) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stages_theta_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Theta_Data.ProtoReflect.Descriptor instead.
func (*Theta_Data) Descriptor() ([]byte, []int) {
	return file_proto_stages_theta_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Theta_Data) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Theta_Data) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Theta_Data) GetAvgRating() float32 {
	if x != nil {
		return x.AvgRating
	}
	return 0
}

var File_proto_stages_theta_proto protoreflect.FileDescriptor

const file_proto_stages_theta_proto_rawDesc = "" +
	"\n" +
	"\x18proto/stages/theta.proto\"t\n" +
	"\x05Theta\x12\x1f\n" +
	"\x04data\x18\x01 \x03(\v2\v.Theta.DataR\x04data\x1aJ\n" +
	"\x04Data\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1c\n" +
	"\tavgRating\x18\x03 \x01(\x02R\tavgRatingB\x1fZ\x1dcommon/communication/protocolb\x06proto3"

var (
	file_proto_stages_theta_proto_rawDescOnce sync.Once
	file_proto_stages_theta_proto_rawDescData []byte
)

func file_proto_stages_theta_proto_rawDescGZIP() []byte {
	file_proto_stages_theta_proto_rawDescOnce.Do(func() {
		file_proto_stages_theta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_stages_theta_proto_rawDesc), len(file_proto_stages_theta_proto_rawDesc)))
	})
	return file_proto_stages_theta_proto_rawDescData
}

var file_proto_stages_theta_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_stages_theta_proto_goTypes = []any{
	(*Theta)(nil),      // 0: Theta
	(*Theta_Data)(nil), // 1: Theta.Data
}
var file_proto_stages_theta_proto_depIdxs = []int32{
	1, // 0: Theta.data:type_name -> Theta.Data
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_stages_theta_proto_init() }
func file_proto_stages_theta_proto_init() {
	if File_proto_stages_theta_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_stages_theta_proto_rawDesc), len(file_proto_stages_theta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_stages_theta_proto_goTypes,
		DependencyIndexes: file_proto_stages_theta_proto_depIdxs,
		MessageInfos:      file_proto_stages_theta_proto_msgTypes,
	}.Build()
	File_proto_stages_theta_proto = out.File
	file_proto_stages_theta_proto_goTypes = nil
	file_proto_stages_theta_proto_depIdxs = nil
}
