// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/stages/zeta.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Zeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Zeta_Data           `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Zeta) Reset() {
	*x = Zeta{}
	mi := &file_proto_stages_zeta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Zeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Zeta) ProtoMessage() {}

func (x *Zeta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stages_zeta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Zeta.ProtoReflect.Descriptor instead.
func (*Zeta) Descriptor() ([]byte, []int) {
	return file_proto_stages_zeta_proto_rawDescGZIP(), []int{0}
}

func (x *Zeta) GetData() []*Zeta_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type Zeta_Data struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*Zeta_Data_Movie_
	//	*Zeta_Data_Rating_
	Data          isZeta_Data_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Zeta_Data) Reset() {
	*x = Zeta_Data{}
	mi := &file_proto_stages_zeta_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Zeta_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Zeta_Data) ProtoMessage() {}

func (x *Zeta_Data) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stages_zeta_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Zeta_Data.ProtoReflect.Descriptor instead.
func (*Zeta_Data) Descriptor() ([]byte, []int) {
	return file_proto_stages_zeta_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Zeta_Data) GetData() isZeta_Data_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Zeta_Data) GetMovie() *Zeta_Data_Movie {
	if x != nil {
		if x, ok := x.Data.(*Zeta_Data_Movie_); ok {
			return x.Movie
		}
	}
	return nil
}

func (x *Zeta_Data) GetRating() *Zeta_Data_Rating {
	if x != nil {
		if x, ok := x.Data.(*Zeta_Data_Rating_); ok {
			return x.Rating
		}
	}
	return nil
}

type isZeta_Data_Data interface {
	isZeta_Data_Data()
}

type Zeta_Data_Movie_ struct {
	Movie *Zeta_Data_Movie `protobuf:"bytes,1,opt,name=movie,proto3,oneof"`
}

type Zeta_Data_Rating_ struct {
	Rating *Zeta_Data_Rating `protobuf:"bytes,2,opt,name=rating,proto3,oneof"`
}

func (*Zeta_Data_Movie_) isZeta_Data_Data() {}

func (*Zeta_Data_Rating_) isZeta_Data_Data() {}

type Zeta_Data_Movie struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       string                 `protobuf:"bytes,1,opt,name=movieId,proto3" json:"movieId,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Zeta_Data_Movie) Reset() {
	*x = Zeta_Data_Movie{}
	mi := &file_proto_stages_zeta_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Zeta_Data_Movie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Zeta_Data_Movie) ProtoMessage() {}

func (x *Zeta_Data_Movie) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stages_zeta_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Zeta_Data_Movie.ProtoReflect.Descriptor instead.
func (*Zeta_Data_Movie) Descriptor() ([]byte, []int) {
	return file_proto_stages_zeta_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Zeta_Data_Movie) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *Zeta_Data_Movie) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type Zeta_Data_Rating struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       string                 `protobuf:"bytes,1,opt,name=movieId,proto3" json:"movieId,omitempty"`
	Rating        float32                `protobuf:"fixed32,2,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Zeta_Data_Rating) Reset() {
	*x = Zeta_Data_Rating{}
	mi := &file_proto_stages_zeta_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Zeta_Data_Rating) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Zeta_Data_Rating) ProtoMessage() {}

func (x *Zeta_Data_Rating) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stages_zeta_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Zeta_Data_Rating.ProtoReflect.Descriptor instead.
func (*Zeta_Data_Rating) Descriptor() ([]byte, []int) {
	return file_proto_stages_zeta_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *Zeta_Data_Rating) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *Zeta_Data_Rating) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

var File_proto_stages_zeta_proto protoreflect.FileDescriptor

const file_proto_stages_zeta_proto_rawDesc = "" +
	"\n" +
	"\x17proto/stages/zeta.proto\"\x83\x02\n" +
	"\x04Zeta\x12\x1e\n" +
	"\x04data\x18\x01 \x03(\v2\n" +
	".Zeta.DataR\x04data\x1a\xda\x01\n" +
	"\x04Data\x12(\n" +
	"\x05movie\x18\x01 \x01(\v2\x10.Zeta.Data.MovieH\x00R\x05movie\x12+\n" +
	"\x06rating\x18\x02 \x01(\v2\x11.Zeta.Data.RatingH\x00R\x06rating\x1a7\n" +
	"\x05Movie\x12\x18\n" +
	"\amovieId\x18\x01 \x01(\tR\amovieId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x1a:\n" +
	"\x06Rating\x12\x18\n" +
	"\amovieId\x18\x01 \x01(\tR\amovieId\x12\x16\n" +
	"\x06rating\x18\x02 \x01(\x02R\x06ratingB\x06\n" +
	"\x04dataB\x1fZ\x1dcommon/communication/protocolb\x06proto3"

var (
	file_proto_stages_zeta_proto_rawDescOnce sync.Once
	file_proto_stages_zeta_proto_rawDescData []byte
)

func file_proto_stages_zeta_proto_rawDescGZIP() []byte {
	file_proto_stages_zeta_proto_rawDescOnce.Do(func() {
		file_proto_stages_zeta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_stages_zeta_proto_rawDesc), len(file_proto_stages_zeta_proto_rawDesc)))
	})
	return file_proto_stages_zeta_proto_rawDescData
}

var file_proto_stages_zeta_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_stages_zeta_proto_goTypes = []any{
	(*Zeta)(nil),             // 0: Zeta
	(*Zeta_Data)(nil),        // 1: Zeta.Data
	(*Zeta_Data_Movie)(nil),  // 2: Zeta.Data.Movie
	(*Zeta_Data_Rating)(nil), // 3: Zeta.Data.Rating
}
var file_proto_stages_zeta_proto_depIdxs = []int32{
	1, // 0: Zeta.data:type_name -> Zeta.Data
	2, // 1: Zeta.Data.movie:type_name -> Zeta.Data.Movie
	3, // 2: Zeta.Data.rating:type_name -> Zeta.Data.Rating
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_stages_zeta_proto_init() }
func file_proto_stages_zeta_proto_init() {
	if File_proto_stages_zeta_proto != nil {
		return
	}
	file_proto_stages_zeta_proto_msgTypes[1].OneofWrappers = []any{
		(*Zeta_Data_Movie_)(nil),
		(*Zeta_Data_Rating_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_stages_zeta_proto_rawDesc), len(file_proto_stages_zeta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_stages_zeta_proto_goTypes,
		DependencyIndexes: file_proto_stages_zeta_proto_depIdxs,
		MessageInfos:      file_proto_stages_zeta_proto_msgTypes,
	}.Build()
	File_proto_stages_zeta_proto = out.File
	file_proto_stages_zeta_proto_goTypes = nil
	file_proto_stages_zeta_proto_depIdxs = nil
}
